class AllCourseContent {
  int id;
  String title;
  String category;
  String student;
  String rating;
  String duration;
  String price;
  String image;
  String mentorImageOne;
  String mentorImageTwo;
  String mentorImageThree;

  AllCourseContent(
      {required this.id,
      required this.title,
      required this.category,
      required this.student,
      required this.rating,
      required this.duration,
      required this.price,
      required this.image,
      required this.mentorImageOne,
      required this.mentorImageTwo,
      required this.mentorImageThree});
}

List<AllCourseContent> allCourseModel = <AllCourseContent>[
  AllCourseContent(
      id: 1,
      title: "Effective Business",
      category: "Business",
      student: "80",
      rating: "4.7",
      duration: "20h 18 min",
      price: "29.99",
      image: "lib/src/assets/all_course/01.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 2,
      title: "Financial Planning",
      category: "Business",
      student: "30",
      rating: "4.9",
      duration: "20h 18 min",
      price: "79.99",
      image: "lib/src/assets/all_course/02.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 3,
      title: "Project Management",
      category: "Business",
      student: "25",
      rating: "4.5",
      duration: "20h 18 min",
      price: "49.99",
      image: "lib/src/assets/all_course/03.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 4,
      title: "Digital Marketing Strategies",
      category: "Business",
      student: "32",
      rating: "4.8",
      duration: "20h 18 min",
      price: "69.99",
      image: "lib/src/assets/all_course/04.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 5,
      title: "Leadership and Team",
      category: "Business",
      student: "28",
      rating: "4.7",
      duration: "20h 18 min",
      price: "89.99",
      image: "lib/src/assets/all_course/05.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 6,
      title: "Web Development",
      category: "Development",
      student: "50",
      rating: "4.6",
      duration: "20h 18 min",
      price: "39.99",
      image: "lib/src/assets/all_course/06.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 7,
      title: "Mobile App Development",
      category: "Development",
      student: "40",
      rating: "4.8",
      duration: "20h 18 min",
      price: "59.99",
      image: "lib/src/assets/all_course/07.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 8,
      title: "Data Science Fundamentals",
      category: "Data Science",
      student: "50",
      rating: "4.6",
      duration: "20h 18 min",
      price: "39.99",
      image: "lib/src/assets/all_course/08.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 9,
      title: "Advanced Data Science",
      category: "Data Science",
      student: "40",
      rating: "4.8",
      duration: "20h 18 min",
      price: "59.99",
      image: "lib/src/assets/all_course/09.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 10,
      title: "Arts and Design Fundamentals",
      category: "Arts and Design",
      student: "50",
      rating: "4.6",
      duration: "20h 18 min",
      price: "39.99",
      image: "lib/src/assets/all_course/10.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 11,
      title: "Advanced Arts and Design Topics",
      category: "Arts and Design",
      student: "40",
      rating: "4.8",
      duration: "20h 18 min",
      price: "59.99",
      image: "lib/src/assets/all_course/11.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 12,
      title: "Finance Fundamentals",
      category: "Finance",
      student: "50",
      rating: "4.6",
      duration: "20h 18 min",
      price: "39.99",
      image: "lib/src/assets/all_course/12.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 13,
      title: "Advanced Finance Topics",
      category: "Finance",
      student: "40",
      rating: "4.8",
      duration: "20h 18 min",
      price: "59.99",
      image: "lib/src/assets/all_course/13.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 14,
      title: "Marketing Fundamentals",
      category: "Marketing",
      student: "50",
      rating: "4.6",
      duration: "20h 18 min",
      price: "39.99",
      image: "lib/src/assets/all_course/14.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 15,
      title: "Advanced Marketing Topics",
      category: "Marketing",
      student: "40",
      rating: "4.8",
      duration: "20h 18 min",
      price: "59.99",
      image: "lib/src/assets/all_course/15.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 16,
      title: "Management Fundamentals",
      category: "Management",
      student: "50",
      rating: "4.6",
      duration: "20h 18 min",
      price: "39.99",
      image: "lib/src/assets/all_course/16.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 17,
      title: "Advanced Management",
      category: "Management",
      student: "40",
      rating: "4.8",
      duration: "20h 18 min",
      price: "59.99",
      image: "lib/src/assets/all_course/17.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 18,
      title: "Fitness Fundamentals",
      category: "Health And Fitness",
      student: "50",
      rating: "4.7",
      duration: "20h 18 min",
      price: "29.99",
      image: "lib/src/assets/all_course/18.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 19,
      title: "Advanced Fitness Topics",
      category: "Health And Fitness",
      student: "25",
      rating: "3.6",
      duration: "20h 18 min",
      price: "59.99",
      image: "lib/src/assets/all_course/19.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 20,
      title: "Photography Fundamentals",
      category: "Photography",
      student: "30",
      rating: "3.9",
      duration: "20h 18 min",
      price: "25.99",
      image: "lib/src/assets/all_course/20.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 21,
      title: "Advanced Photography",
      category: "Photography",
      student: "26",
      rating: "3.7",
      duration: "20h 18 min",
      price: "22.99",
      image: "lib/src/assets/all_course/21.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 22,
      title: "Music Fundamentals",
      category: "Music",
      student: "47",
      rating: "4.6",
      duration: "20h 18 min",
      price: "39.99",
      image: "lib/src/assets/all_course/22.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png"),
  AllCourseContent(
      id: 23,
      title: "Advanced Music Topics",
      category: "Music",
      student: "30",
      rating: "4.9",
      duration: "20h 18 min",
      price: "49.99",
      image: "lib/src/assets/all_course/23.jpg",
      mentorImageOne: "lib/src/assets/mentor/mentor_1.png",
      mentorImageTwo: "lib/src/assets/mentor/mentor_2.png",
      mentorImageThree: "lib/src/assets/mentor/mentor_3.png")
];
